[config]
mode = "pkg" # configs mirror into ~/.config/
# stow = ["zsh"]       # these configs mirror into $HOME (GNU stow style)
# mode = "stow"        # make every config stow-style

# [modules]
# on = ["nvim"]        # top-level dirs that are their own roots
#                      # (own pkg.toml + configs/)

[[system]]
packages = [
    "bash-language-server",
    "bluetui",
    "clang",
    "cliamp",
    "cliampt",
    "cloc",
    "fish",
    "flatpak",
    "ghostty",
    "glxinfo",
    "go",
    "gopls",
    "helix",
    "herdr",
    "kitty",
    "lazygit",
    "lib32-mesa",
    "ltext-ls-plus",
    "lua-language-server",
    "man-pages",
    "markdown-oxide",
    "marksman",
    "mesa-demos",
    "nvim",
    "nyxt",
    "ols",
    "opencode",
    "prettier",
    "pyright",
    "python",
    "python-black",
    "qutebrowser",
    "rust-analyzer",
    "rustfmt",
    "rustup",
    "shfmt",
    "starship",
    "taplo",
    "tmux",
    "typescript-language-server",
    "zig",
    "zls",
]

[hooks]
