theme = "ayu_dark"

[editor]
cursorline = true
scrolloff = 8
bufferline = "multiple"
idle-timeout = 0
rulers = [100]
true-color = true
completion-replace = true
trim-trailing-whitespace = true
insert-final-newline = true
auto-pairs = true
popup-border = "menu"
end-of-line-diagnostics = "hint"
auto-format = true
completion-timeout = 0
auto-info = true
shell = ["fish", "-c"]

[editor.smart-tab]
enable = true

[editor.whitespace.render]
space = "none"
tab =   "all"

[editor.soft-wrap]
enable = true

[editor.lsp]
display-inlay-hints = true
inlay-hints-length-limit = 15

[editor.cursor-shape]
insert = "bar"
select = "underline"


[keys.normal]
C-h = "jump_view_left"
C-j = "jump_view_down"
C-k = "jump_view_up"
C-l = "jump_view_right"
C-g = [":new", ":insert-output lazygit", ":buffer-close!", ":redraw"]
tab = "command_mode"

[keys.insert]
C-h = "jump_view_left"
C-j = "jump_view_down"
C-k = "jump_view_up"
C-l = "jump_view_right"
C-g = [":new", ":insert-output lazygit", ":buffer-close!", ":redraw"]
j = { k = "normal_mode" }
