format = """
$directory$git_branch
$character"""

[directory]
style = "bold blue"
truncation_length = 3
truncate_to_repo = true

[git_branch]
format = "$symbol$branch"
symbol = ""
style = "bold purple"

[character]
success_symbol = "[λ ](bold green)"
error_symbol = "[λ ](bold red)"
